import localFont from "next/font/local";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import { useQuery,
  useMutation,
  useQueryClient,
  QueryClient,
  QueryClientProvider,} from "@tanstack/react-query";
import { SqProvider } from "@/components/SqProvider";

// const queryClient = new QueryClient();

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <SqProvider>
    <html lang="es">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}
        >
          <Sidebar />
          {children}
        </body>
      </html>
        </SqProvider>
  );
}
